# Licensed under the Apache License, Version 2.0. See LICENSE for details.
quarkus.application.name=jackson-generated-benchmark
quarkus.banner.enabled=false
quarkus.http.host-enabled=false
quarkus.log.console.enabled=false
quarkus.package.output-name=jackson-generated-benchmark
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
